# Generated by Django 3.1.3 on 2020-12-15 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='light',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='node',
            name='moisture',
            field=models.IntegerField(default=0),
        ),
    ]
