# Generated by Django 3.1.3 on 2020-12-15 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20201215_0716'),
    ]

    operations = [
        migrations.RenameField(
            model_name='node',
            old_name='device_id',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='node',
            name='user',
        ),
    ]
